version: '3'
services:
  docker-mysql:
    image: mysql
    ports:
      - "3301:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=fitapp
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_PASSWORD=pass

  spring-webap:
    build:
      dockerfile: Dockerfile
      context: .
    image: fitapp:1.0
    depends_on:
      - docker-mysql
    ports:
      - 8092:8080
    environment:
      SPRING_PROFILES_ACTIVE: local